### PR TITLE
renaming `master` branch to `main`

### PR DESCRIPTION
**Pull request by jvanasco**
This PR to the "master" branch replaces all occurrences of the "master" branch with "main".  

I believe the two options to handle the rename are:

* copy "master" to "main", set that as default, merge this PR.
or
* merge this PR to "master", then rename to "main" and set that as default.

See also:: https://github.com/Pylons/pyramid/issues/3712

### CODE REVIEW

**Comment by stevepiercy** [comment]
Please resolve the merge conflicts.

**Review by stevepiercy — APPROVED** [review]

**Comment by jvanasco** [comment]
@stevepiercy I'm going to abort this PR and start from scratch. Somehow the origin and local copies broke with the upstream.

**Comment by jvanasco** [comment]
@stevepiercy I think things broke because of some issues with the repo.

According to the README:

* latest aligns with the latest stable release of Pyramid, and is the default branch on GitHub.
* master aligns with the master branch of Pyramid, and is where development takes place.

however, look at the commit histories here:

* master has 202 commits, https://github.com/Pylons/pyramid-cookiecutter-starter/commits/master , the most recent being Mar 29, 2021 #596107a1dbee59a25a2d5008260085f4fa1f3eb6

* latest has 235 commits, https://github.com/Pylons/pyramid-cookiecutter-starter/commits/latest, the most recent being Feb 28 2021 #23d6491fd5c7014990dfbbff45c07dbfdc8b9be1

It seems these two diverged quite a bit at some point.  Shouldn't `latest` have fewer commits than `master` ?

**Comment by stevepiercy** [comment]
I don't know about commit counts. Some people make many small commits, and others make one big one. I would not give it any weight.

If the issue is lack of development, yeah, it's been very quiet in here since 2.0 was released on 2021-02-28. That is expected.

Between Pyramid and this cookiecutter, the `master` branches align, whereas `latest` here now aligns with `2.0-branch` (and before that `1.10-branch`, `1.9-branch`, and so on) in Pyramid.

What is the problem you see?

**Comment by jvanasco** [comment]
Based on the description, I assume that "master" would have the full commit history of "latest".  (i.e. latest is branched off master).  Were these two branches independently developed?

**Comment by stevepiercy** [comment]
A branch may diverge from master because we're fixing bugs on that branch, just like in Pyramid.

**Comment by jvanasco** [comment]
resubmitted in #118

**Pull request closed without merging**
