### PR TITLE
Add logger_alembic to ini files

### PR DESCRIPTION
**Pull request by silenius**
Add missing alembic logger

### CODE REVIEW

**Review by stevepiercy — APPROVED** [review]
LGTM.

Before merging, we need updates to the Pyramid repo on `master` for wherever these files are found, specifically in the tutorials and I think in a few of the narrative docs as well. I've created a new issue to track changes.

https://github.com/Pylons/pyramid/issues/3523

Then when master is updated, I can do a backport to `1.10-branch` on Pyramid and to `latest` branch here.

**Comment by stevepiercy** [comment]
@mmerickel do we care about the failing test on Python 3.4 in this PR? I think we should just drop support for Python 3.4 now in the cookiecutter, unless there is a compelling reason to keep it 100% aligned with Pyramid.

**Comment by mmerickel** [comment]
Yes drop 3.4.

**Comment by stevepiercy** [comment]
I'm merging this PR, ignoring the failure for 3.4, the support for which I will drop in a separate PR on master.

**Comment by stevepiercy** [comment]
Thank you @silenius!

**Pull request merged**
