### PR TITLE
Use the correct number of = to make a title.

### PR DESCRIPTION
**Pull request by Natim**

### CODE REVIEW

**Comment by stevepiercy** [comment]
This is nice. Would you please sign [CONTRIBUTORS.txt](https://github.com/Pylons/pyramid-cookiecutter-starter/blob/master/CONTRIBUTORS.txt), and push that commit? It will automatically update the PR.

This should also be applied to the other two cookiecutters, https://github.com/Pylons/pyramid-cookiecutter-alchemy and https://github.com/Pylons/pyramid-cookiecutter-zodb. If you feel inclined to submit PRs for those two as well, I would appreciate it.

Also before I merge, I need to review the Pyramid docs for these rendered files, and update accordingly. Example:
https://github.com/Pylons/pyramid/blob/master/docs/narr/myproject/README.txt#L2

**Comment by Natim** [comment]
Ok @stevepiercy thanks for the guidance.

**Comment by Natim** [comment]
- Refs https://github.com/Pylons/pyramid-cookiecutter-zodb/pull/7
- Refs https://github.com/Pylons/pyramid-cookiecutter-alchemy/pull/8

**Comment by stevepiercy** [comment]
Thank you!

**Pull request merged**
