### PR TITLE
Update README.rst to be agnostic toward backend choice

### PR DESCRIPTION
**Pull request by stevepiercy**
- Make indentation consistent to 4 spaces

### CODE REVIEW

**Comment by stevepiercy** [comment]
See also #85 and https://youtrack.jetbrains.com/issue/PY-40998

**Comment by stevepiercy** [comment]
@mmerickel I made three different PRs, one each to `master`, `latest`, and `1.10-branch`. I know that the branches can be tricky, so I'd appreciate a review to ensure I didn't cross wires.

**Comment by mmerickel** [comment]
The previous instructions do not say anything about a database. These are super generic setup instructions that any project needs to do at the beginning. If you want to add an extra step at the end to point at the project-specific readme then fine, but this change seems worse to me.

**Comment by stevepiercy** [comment]
> The previous instructions do not say anything about a database.

That is an artifact left over from when starter did not offer a database. It was an oversight that we did not update the instructions (which would have been a challenge, given all the choices and their subsequent evolution to include alembic migrations), although we updated the description of the project at the top.

> this change seems worse to me

What would improve it? Leaving it as is is misleading and worse than this proposal.

**Comment by mmerickel** [comment]
These instructions are the base that all versions rely on to get started. Like I said if you want you should just add another step afterward to tell them to go read the project-specific setup instructions in their own readme. Just add you new sentence as another step. There’s no reason imo to get rid of these shared steps so people get a feel for the base requirements.

**Comment by stevepiercy** [comment]
@mmerickel I made some revisions. Would you please take another look? If it's good, I'll apply to the other branches. Thank you!

**Review by mmerickel — APPROVED** [review]
It's fine. Again these steps are the precursor to the custom steps... they come **before** the extra steps in the sqlalchemy backend so you could just add a final step to go check and perform the rest of the stuff in the readme.

**Comment by stevepiercy** [comment]
The sqlalchemy step must come after the default set of steps and before running tests or the app, so I put it there instead of at the end.

I also made text from the console output to align with the `README.txt`. @mmerickel would you please give one last review?

**Review by mmerickel — APPROVED** [review]

**Pull request merged**
